-- CREATE TABLE "businesses" (
-- 	"id" serial PRIMARY KEY NOT NULL,
-- 	"user_id" integer NOT NULL,
-- 	"business_name" text NOT NULL,
-- 	"address" text,
-- 	"phone" varchar(20),
-- 	"website" text
-- );
-- --> statement-breakpoint
-- ALTER TABLE "businesses" ADD CONSTRAINT "businesses_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;