INSERT INTO "demographics" ("name", "category") VALUES
('Male', 'Gender'),
('Female', 'Gender'),
('Non-binary', 'Gender'),
('Prefer not to say', 'Gender'),
('White', 'Race'),
('Black or African American', 'Race'),
('Asian', 'Race'),
('American Indian or Alaska Native', 'Race'),
('Native Hawaiian or Other Pacific Islander', 'Race'),
('Hispanic or Latino', 'Race'),
('Two or More Races', 'Race'),
('Other', 'Race'),
('Christianity', 'Religion'),
('Islam', 'Religion'),
('Judaism', 'Religion'),
('Hinduism', 'Religion'),
('Buddhism', 'Religion'),
('Atheist', 'Religion'),
('Agnostic', 'Religion'),
('Other', 'Religion');