-- One-line summaries for the seeded units (only fills blanks). Applied by: npm run db:apply

UPDATE "lessons" l SET "summary" = 'Define entrepreneurship and social innovation, name the problem you''re solving, and back it with data.', "updated_at" = now() FROM "classes" c WHERE l."class_id" = c."id" AND c."title" = 'Heighten The Hustle™ Core Curriculum' AND l."order" = 1 AND (l."summary" IS NULL OR l."summary" = '');
UPDATE "lessons" l SET "summary" = 'Map your competitors, understand why customers choose them, and pin down what you do differently.', "updated_at" = now() FROM "classes" c WHERE l."class_id" = c."id" AND c."title" = 'Heighten The Hustle™ Core Curriculum' AND l."order" = 2 AND (l."summary" IS NULL OR l."summary" = '');
UPDATE "lessons" l SET "summary" = 'Profile your ideal customer, how they find you, and how you''ll win them. Guest speaker: Nkenge Yasin.', "updated_at" = now() FROM "classes" c WHERE l."class_id" = c."id" AND c."title" = 'Heighten The Hustle™ Core Curriculum' AND l."order" = 3 AND (l."summary" IS NULL OR l."summary" = '');
UPDATE "lessons" l SET "summary" = 'List the services you charge for and start the Fee and Expense Template.', "updated_at" = now() FROM "classes" c WHERE l."class_id" = c."id" AND c."title" = 'Heighten The Hustle™ Core Curriculum' AND l."order" = 4 AND (l."summary" IS NULL OR l."summary" = '');
UPDATE "lessons" l SET "summary" = 'Set your prices and work out what each service costs you to deliver.', "updated_at" = now() FROM "classes" c WHERE l."class_id" = c."id" AND c."title" = 'Heighten The Hustle™ Core Curriculum' AND l."order" = 5 AND (l."summary" IS NULL OR l."summary" = '');
UPDATE "lessons" l SET "summary" = 'Build a 24-month and 8-year revenue and expense forecast, then calculate profit.', "updated_at" = now() FROM "classes" c WHERE l."class_id" = c."id" AND c."title" = 'Heighten The Hustle™ Core Curriculum' AND l."order" = 6 AND (l."summary" IS NULL OR l."summary" = '');
UPDATE "lessons" l SET "summary" = 'Plan how the business grows, the talent you''ll need, and how to fund that growth.', "updated_at" = now() FROM "classes" c WHERE l."class_id" = c."id" AND c."title" = 'Heighten The Hustle™ Core Curriculum' AND l."order" = 7 AND (l."summary" IS NULL OR l."summary" = '');
UPDATE "lessons" l SET "summary" = 'Get oriented with the Lean Canvas and the Business Plan Summary you''ll complete over the next units.', "updated_at" = now() FROM "classes" c WHERE l."class_id" = c."id" AND c."title" = 'Heighten The Hustle™ Core Curriculum' AND l."order" = 8 AND (l."summary" IS NULL OR l."summary" = '');
UPDATE "lessons" l SET "summary" = 'Lean Canvas components 1 and 2: the Problem and the Customer.', "updated_at" = now() FROM "classes" c WHERE l."class_id" = c."id" AND c."title" = 'Heighten The Hustle™ Core Curriculum' AND l."order" = 9 AND (l."summary" IS NULL OR l."summary" = '');
UPDATE "lessons" l SET "summary" = 'Lean Canvas component 3: your Unique Value Proposition.', "updated_at" = now() FROM "classes" c WHERE l."class_id" = c."id" AND c."title" = 'Heighten The Hustle™ Core Curriculum' AND l."order" = 10 AND (l."summary" IS NULL OR l."summary" = '');
UPDATE "lessons" l SET "summary" = 'Lean Canvas components 4 and 5: Solution and Key Benefits / Unfair Advantage. Intro to pitching.', "updated_at" = now() FROM "classes" c WHERE l."class_id" = c."id" AND c."title" = 'Heighten The Hustle™ Core Curriculum' AND l."order" = 11 AND (l."summary" IS NULL OR l."summary" = '');
UPDATE "lessons" l SET "summary" = 'Lean Canvas components 6 and 7: Revenue Streams and Cost Structure.', "updated_at" = now() FROM "classes" c WHERE l."class_id" = c."id" AND c."title" = 'Heighten The Hustle™ Core Curriculum' AND l."order" = 12 AND (l."summary" IS NULL OR l."summary" = '');
UPDATE "lessons" l SET "summary" = 'Lean Canvas components 8 and 9: Key Metrics and Channels, plus a review of your Business Plan Summary.', "updated_at" = now() FROM "classes" c WHERE l."class_id" = c."id" AND c."title" = 'Heighten The Hustle™ Core Curriculum' AND l."order" = 13 AND (l."summary" IS NULL OR l."summary" = '');
UPDATE "lessons" l SET "summary" = 'Draft your pitch deck and start practicing in front of the cohort.', "updated_at" = now() FROM "classes" c WHERE l."class_id" = c."id" AND c."title" = 'Heighten The Hustle™ Core Curriculum' AND l."order" = 14 AND (l."summary" IS NULL OR l."summary" = '');
UPDATE "lessons" l SET "summary" = 'More pitch practice with feedback, and final polish on the deck.', "updated_at" = now() FROM "classes" c WHERE l."class_id" = c."id" AND c."title" = 'Heighten The Hustle™ Core Curriculum' AND l."order" = 15 AND (l."summary" IS NULL OR l."summary" = '');
UPDATE "lessons" l SET "summary" = 'Deliver your business plan pitch.', "updated_at" = now() FROM "classes" c WHERE l."class_id" = c."id" AND c."title" = 'Heighten The Hustle™ Core Curriculum' AND l."order" = 16 AND (l."summary" IS NULL OR l."summary" = '');
